// <auto-generated />
namespace SportSquare.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VenueId_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VenueId_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201702122109131_VenueId_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
